# Experiment 2: Fundamentals of NumPy

This experiment covers the core concepts and operations of NumPy, including:
- Version Verification
- Array Creation (0D, 1D, 2D, Ones)
- Array Indexing & Slicing
- Element-wise Operations
- Aggregations (Sum, Mean, Std)
- Boolean Masking & Fancy Indexing
- Array Reshaping
- Structured Arrays

## 1. NumPy Version Verification

In [1]:
import numpy as np

# Check NumPy version
print("NumPy Version:", np.__version__)

NumPy Version: 2.2.6


## 2. Array Creation

In [2]:
# Creating different types of arrays
arr_0d = np.array(42)
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_ones = np.ones((3, 3))

print("0D Array:", arr_0d)
print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
print("3x3 Ones Array:\n", arr_ones)

0D Array: 42
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3x3 Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3. Indexing and Slicing

In [3]:
# Indexing and Slicing
print("Element at index 2 in 1D array:", arr_1d[2])
print("Element at row 1, column 2 in 2D array:", arr_2d[1, 2])
print("Slice from 1D array:", arr_1d[1:4])
print("Slice row 1 from 2D array:", arr_2d[1, :])

Element at index 2 in 1D array: 3
Element at row 1, column 2 in 2D array: 6
Slice from 1D array: [2 3 4]
Slice row 1 from 2D array: [4 5 6]


## 4. Element-wise Operations

In [4]:
# Element-wise operations
arr_a = np.array([10, 20, 30])
arr_b = np.array([1, 2, 3])

print("Addition:", arr_a + arr_b)
print("Subtraction:", arr_a - arr_b)
print("Multiplication:", arr_a * arr_b)
print("Division:", arr_a / arr_b)
print("Scalar Multiplication:", arr_a * 2)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [ 10  40  90]
Division: [10. 10. 10.]
Scalar Multiplication: [20 40 60]


## 5. Statistical Aggregations

In [5]:
# Aggregations
print("Sum:", np.sum(arr_a))
print("Mean:", np.mean(arr_a))
print("Standard Deviation:", np.std(arr_a))

Sum: 60
Mean: 20.0
Standard Deviation: 8.16496580927726


## 6. Comparison, Boolean Masking & Fancy Indexing

In [6]:
# Element-wise comparison
print("Element-wise comparison:", arr_a > arr_b)

# Boolean masking
print("Elements greater than 15:", arr_a[arr_a > 15])

# Fancy Indexing
indices = [0, 2]
print("Selected elements:", arr_a[indices])

Element-wise comparison: [ True  True  True]
Elements greater than 15: [20 30]
Selected elements: [10 30]


## 7. Reshaping & Structured Arrays

In [7]:
# Reshape
reshaped_arr = arr_1d.reshape(5, 1)
print("Reshaped 1D array to 2D:\n", reshaped_arr)

# Structured array
structured_arr = np.array([(25, 90.5), (30, 85.2)], dtype=[('age', 'i4'), ('score', 'f4')])
print("Structured array:", structured_arr)

Reshaped 1D array to 2D:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Structured array: [(25, 90.5) (30, 85.2)]
